########################################
## Raw
########################################
Ivoz\Provider\Domain\Model\DestinationRate\Name:
Ivoz\Provider\Domain\Model\DestinationRate\Description:
Ivoz\Provider\Domain\Model\DestinationRate\DestinationRate:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
Ivoz\Provider\Domain\Model\RatingPlan\Name:
Ivoz\Provider\Domain\Model\RatingPlan\Description:
Ivoz\Provider\Domain\Model\RatingPlan\RatingPlan:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
Ivoz\Cgr\Domain\Model\TpDestination\TpDestination:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
Ivoz\Cgr\Domain\Model\TpRate\TpRate:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
Ivoz\Cgr\Domain\Model\TpDestinationRate\Destination:
Ivoz\Cgr\Domain\Model\TpDestinationRate\Rate:
Ivoz\Cgr\Domain\Model\TpDestinationRate\TpDestinationRate:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
Ivoz\Cgr\Domain\Model\TpRatingPlan\TpRatingPlan:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
Ivoz\Cgr\Domain\Model\TpRatingProfile\TpRatingProfile:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
