#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: callCsvSchedulersList_screen
  screens: &callCsvSchedulers_screensLink

    callCsvSchedulersList_screen: &callCsvSchedulersList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *CallCsvSchedulers
      class: ui-silk-report-key
      title: _("List of %s %2s", ngettext('Call CSV scheduler', 'Call CSV schedulers', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields: &callCsvSchedulers_fieldsLink
        options:
          title: _("Options")
          screens:
            callCsvSchedulersEdit_screen: true
          dialogs:
            callCsvSchedulersDel_dialog: true
          default: callCsvSchedulersEdit_screen
        order:
          name: true
          company: true
          frecuency: true
          unit: true
        blacklist:
          email: true
          lastExecution: true
      options:
        title: _("Options")
        screens:
          callCsvSchedulersNew_screen: true
        dialogs:
          callCsvSchedulersDel_dialog: true

    callCsvSchedulersNew_screen: &callCsvSchedulersNew_screenLink
      <<: *CallCsvSchedulers
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Call CSV scheduler', 'Call CSV schedulers', 1), "[format| (%parent%)]")
      fullWidth: true
      forcedValues:
        <<: *forcedCompany
      shortcutOption: N
      fields:
        blacklist:
          lastExecution: true
          nextExecution: true
      fixedPositions: &callCsvSchedulersFixedPositions_Link
        group0:
          colsPerRow: 2
          fields:
            name: 1
            company: true
            email: 1
            nextExecution: 1
            lastExecution: 1
        group1:
          colsPerRow: 2
          fields:
            frequency: 1
            unit: 1

    callCsvSchedulersEdit_screen: &callCsvSchedulersEdit_screenLink
      <<: *CallCsvSchedulers
      controller: edit
      class: ui-silk-pencil
      label: false
      fullWidth: true
      title: _("Edit %s %2s", ngettext('Call CSV scheduler', 'Call CSV schedulers', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        readOnly:
          nextExecutin: true
      fixedPositions:
        <<: *callCsvSchedulersFixedPositions_Link

  dialogs: &callCsvSchedulers_dialogsLink
    callCsvSchedulersDel_dialog: &callCsvSchedulersDel_dialogLink
      <<: *CallCsvSchedulers
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Call CSV scheduler', 'Call CSV schedulers', 1))
      description: _("Do you want to delete this %s?", ngettext('Call CSV scheduler', 'Call CSV schedulers', 1))
      message: _("%s successfully deleted.", ngettext('Call CSV scheduler', 'Call CSV schedulers', 1))
      multiItem: 1
      labelOnList: 1


staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
