Ivoz\Provider\Domain\Model\CallCsvScheduler\CallCsvSchedulerAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    invoiceScheduler_name_company:
      columns:
        - name
        - companyId
  fields:
    name:
      type: string
      nullable: false
      length: 40
      options:
        fixed: false
    unit:
      type: string
      nullable: false
      length: 30
      options:
        fixed: false
        comment: '[enum:week|month|year]'
        default: 'month'
    frequency:
      type: smallint
      nullable: false
      options:
        unsigned: true
    email:
      type: string
      nullable: false
      length: 140
      options:
        fixed: false
    lastExecution:
      type: datetime
      nullable: true
      column: lastExecution
    nextExecution:
      type: datetime
      nullable: true
      column: nextExecution
  manyToOne:
    company:
      targetEntity: \Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
