Ivoz\Provider\Domain\Model\RatingPlan\RatingPlan:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\RatingPlanDoctrineRepository
  type: entity
  table: RatingPlans
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
