Ivoz\Provider\Domain\Model\RatingProfile\RatingProfile:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\RatingProfileDoctrineRepository
  type: entity
  table: RatingProfiles
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
