Ivoz\Provider\Domain\Model\RatingPlan\RatingPlanAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    brandTag:
      columns:
        - tag
        - brandId
  embedded:
    name:
      class: Name
      columnPrefix: false
    description:
      class: Description
      columnPrefix: false
  fields:
    tag:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false