Ivoz\Provider\Domain\Model\RatingPlan\Description:
  type: embeddable
  fields:
    en:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
      column: description_en
    es:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
      column: description_es
